home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    ]

store/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('product', include('store1.urls')),
    path('__debug__/', include(debug_toolbar.urls)),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store1/urls.py
from django.urls import path

from . import views

app_name = 'store1'
urlpatterns = [
    path('', views.product_list, name='store1'),
    path('<int:pk>', views.product, name="product")
]

home/models.py
from django.db import models

# Create your models here.

store1/models.py
from django.db import models
from django.utils.text import slugify


class Product(models.Model):
    name = models.CharField(max_length=100)
    stock_count = models.IntegerField(help_text="How many items are currently in stock.")
    price = models.DecimalField(max_digits=5, decimal_places=2)
    description = models.TextField(default="", blank=True)
    sku = models.CharField(max_length=20, unique=True, verbose_name="Stock Keeping Unit")
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)

        return super().save(*args, **kwargs)


class Category(models.Model):
    name = models.CharField(max_length=100)
    product = models.ManyToManyField("Product", related_name='categories')

    def __str__(self):
        return f'{self.name}'


class ProductImage(models.Model):
    image = models.ImageField()
    product = models.ForeignKey('Product', on_delete=models.CASCADE, related_name='images')

    def __str__(self):
        return f'{self.image}'

store1/forms.py
from django.forms import ModelForm
from . import models


class ProductForm(ModelForm):
    class Meta:
        model= models.Product
        field = "__all__"

home/views.py
from django.shortcuts import render

# Create your views here.


def home(request):
    return render(request, 'home/home.html')

store1/views.py
from django.shortcuts import render, get_object_or_404
from store1.models import Product

from store1.models import ProductImage


def product_list(request):
    products = Product.objects.all()
    return render(request, "store1/products.html", {'products': products})


def product(request, pk):
    item = get_object_or_404(Product, pk=pk)
   # product_image = Product.objects.filter(pk=pk).prefetch_related('images').first()
    images = item.images.all()
    print(images)


    return render(request, 'store1/product.html', {'product': item, "im": images})

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Home
{% endblock %}

{% block scripts %}
<script src="{% static 'scripts/main.js' %}"async defer></script>
{% endblock %}

{% block container %}
<h1>Store - Welcome</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium corporis, cupiditate distinctio esse est eveniet ex excepturi, inventore ipsa labore magnam natus odio officiis perferendis quos, sit suscipit totam.</p>
{% endblock %}

{% block aside %}
    <h3>Comes from home.html Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad aliquid at cum esse eum id officia repudiandae sint tenetur ut.</h3>
{% endblock %}

store1/templates/store1/product.html
{% extends 'base.html' %}

{% block title %}Products{% endblock %}

{% block container %}
<div class="card" style="width: 18rem;">

  <img src="/media/{{ product.images }}" class="card-img-top" alt="">
  <div class="card-body">
    <h5 class="card-title">{{product.name }}</h5>
    <p class="card-text">{{product.description}}</p>

  </div>
</div>

{% endblock %}

store1/templates/store1/products.html
{% extends 'base.html' %}

{% block title %}Products{% endblock %}

{% block container %}
    <h1>Products</h1>

    <ul>
        {% for product in products %}
            <li>
                <a href="{% url 'store1:product' product.pk%}"><span>Name: {{ product.name }}</span></a>
            </li>
            {% empty %}
            <p>0 products</p>

        {% endfor %}
    </ul>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Store-{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href=" {% static 'styles/bootstrap.min.css' %}">
    <link rel="stylesheet" href=" {% static 'styles/main.css' %}">
  {% block scripts %}
<script src="{% static 'scripts/main.js' %}"async defer></script>
{% endblock %}

</head>
<body>


<button type="button" class="btn btn-link">Link</button>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

<div class="container">
  <div class="row">
    <div class="col">{% block aside %}

{% endblock %}</div>
    <div class="col"></div>
  </div>
</div>

{% block container %}

{% endblock %}

</body>
</html>